api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}
  traefik:
    address: ":8080"

ping:
  entryPoint: traefik

providers:
  docker:
    exposedByDefault: false
    network: homelab
  file:
    directory: /etc/traefik/dynamic/
    watch: true

log:
  level: INFO

accessLog: {}

# metrics:
#   prometheus:
#     entryPoint: traefik
#     addEntryPointsLabels: true
#     addRouterLabels: true
#     addServicesLabels: true

# certificatesResolvers:
#   le:
#     acme:
#       email: admin@silencelie.dev
#       storage: /etc/traefik/acme.json
#       httpChallenge:
#         entryPoint: web
#       dnsChallenge:
#         provider: cloudflare
#         delayBeforeCheck: 0